export const styles = {
  // ── CONTAINER GERAL ──
  pageContainer: {
    display: 'flex',
    minHeight: '100vh',
    width: '100%',
  },

  // ── LADO ESQUERDO (visual / institucional) ──
  ladoVisual: {
    flex: '1',
    backgroundColor: '#0F4C81',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    color: 'white',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '60px 40px',
    textAlign: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  overlayLadoVisual: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 76, 129, 0.75)',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
  },
  conteudoLadoVisual: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  logoLadoVisual: {
    height: '70px',
    marginBottom: '25px',
  },
  tituloLadoVisual: {
    fontSize: '1.8rem',
    fontWeight: '700',
    marginBottom: '15px',
    lineHeight: '1.3',
  },
  textoLadoVisual: {
    fontSize: '1rem',
    opacity: 0.85,
    maxWidth: '380px',
    lineHeight: '1.6',
  },

  // ── LADO DIREITO (formulário) ──
  ladoForm: {
    flex: '1',
    backgroundColor: '#ffffff',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '40px',
  },
  formWrapper: {
    width: '100%',
    maxWidth: '380px',
  },
  tituloForm: {
    color: '#0F4C81',
    fontSize: '1.7rem',
    fontWeight: '700',
    marginBottom: '8px',
  },
  subtituloForm: {
    color: '#666',
    fontSize: '0.95rem',
    marginBottom: '35px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginBottom: '20px',
  },
  label: {
    fontSize: '0.9rem',
    fontWeight: '600',
    color: '#333',
  },
  inputWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  iconeInput: {
    position: 'absolute',
    left: '14px',
    color: '#888',
    display: 'flex',
    alignItems: 'center',
    pointerEvents: 'none',
  },
  input: {
    width: '100%',
    padding: '13px 14px 13px 42px',
    borderRadius: '8px',
    border: '1.5px solid #ddd',
    fontSize: '0.95rem',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  iconeSenhaToggle: {
    position: 'absolute',
    right: '14px',
    color: '#888',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    background: 'none',
    border: 'none',
    padding: 0,
  },
  erroTexto: {
    color: '#dc2626',
    fontSize: '0.85rem',
    marginTop: '-12px',
    marginBottom: '18px',
  },
  btnEntrar: {
    width: '100%',
    backgroundColor: '#0F4C81',
    color: 'white',
    padding: '14px',
    border: 'none',
    borderRadius: '8px',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    marginTop: '10px',
    transition: 'background-color 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  },
  linkVoltar: {
    display: 'block',
    textAlign: 'center',
    marginTop: '25px',
    color: '#666',
    fontSize: '0.9rem',
    textDecoration: 'none',
    cursor: 'pointer',
  },
  avisoRestrito: {
    backgroundColor: '#f0f4f8',
    border: '1px solid #d8e3ee',
    borderRadius: '8px',
    padding: '12px 16px',
    fontSize: '0.82rem',
    color: '#555',
    marginTop: '25px',
    lineHeight: '1.5',
  },
};
